[project]
name = "ocr"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mineru[core]",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "python-dotenv",
    "latex2mathml>=3.81.0",
    "mathml2omml>=0.0.2",
    "boto3>=1.43.53",
]

[tool.uv.sources]
mineru = { workspace = true }

[tool.uv.workspace]
members = ["MinerU"]
